### PR TITLE
Added WindowBounds memory for the main window.

### PR DESCRIPTION
**Pull request by nicost**
Derived from code in Micro-Manager, but uses Java preferences to store settings.  it would be preferable to add a way to pass a key to NDVIewer for instance to tie the location to the user who is actually using it, but that will need additions to the API. Let me know if I should add that.

### CODE REVIEW

**Comment by henrypinkard** [comment]
Yes, If you think that makes sense, go for it!

**Comment by henrypinkard** [comment]
When you're ready, to get this to go into the nightly build, you'll need to change the version number in the pom.xml. When it merges, it will auto deploy to sonatype, then if you change the version number in ivy.xml it should get included

**Comment by nicost** [comment]
Should be ready to merge now. I'll leave the honors to you;)  

B.t.w., I think it would make sense to bump the version to 1.0 and start using semver versioning.  That will make it more clear what kind of changes can be expected between different versions.  In accordance with semver, I bumped the version to 0.6.0 (addition of a method, no incompatible changes to api).

**Comment by henrypinkard** [comment]
Nice!

**Comment by henrypinkard** [comment]
Yeah I think that makes sense about the versioning. Also feel free to make more changes as you see fit to make it work better with your workflows

**Comment by henrypinkard** [comment]
Looks like there are compilation/build problems: You're using a google dependency that it doesn't have?

https://github.com/micro-manager/NDViewer/actions/runs/3352215704/jobs/5554209971

You can try doing a local build `mvn clean package` to test if the action will run correctly

**Pull request merged**
